/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-background": "#1c1b1b",
        "primary-fixed-dim": "#a5d0b9",
        "on-primary-fixed-variant": "#274e3d",
        "on-primary": "#ffffff",
        "on-primary-container": "#86af99",
        "primary-container": "#1b4332",
        "on-tertiary-fixed": "#241a00",
        "tertiary-container": "#cba72f",
        "on-surface": "#1c1b1b",
        "tertiary-fixed-dim": "#e9c349",
        "on-error-container": "#93000a",
        "on-secondary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#c1ecd4",
        "on-error": "#ffffff",
        "on-surface-variant": "#414844",
        "on-tertiary": "#ffffff",
        "tertiary": "#735c00",
        "background": "#fcf9f8",
        "error-container": "#ffdad6",
        "on-tertiary-container": "#4e3d00",
        "on-secondary-fixed": "#1b1c1c",
        "inverse-primary": "#a5d0b9",
        "tertiary-fixed": "#ffe088",
        "on-primary-fixed": "#002114",
        "surface-tint": "#3f6653",
        "surface-dim": "#dcd9d9",
        "secondary-fixed-dim": "#c8c6c5",
        "outline": "#717973",
        "on-tertiary-fixed-variant": "#574500",
        "surface-container-high": "#ebe7e7",
        "inverse-surface": "#313030",
        "surface-variant": "#e5e2e1",
        "on-secondary-container": "#656464",
        "surface-container": "#f0edec",
        "secondary-fixed": "#e4e2e1",
        "outline-variant": "#c1c8c2",
        "primary": "#012d1d",
        "surface-container-highest": "#e5e2e1",
        "secondary-container": "#e4e2e1",
        "error": "#ba1a1a",
        "secondary": "#5f5e5e",
        "surface-container-low": "#f6f3f2",
        "surface": "#fcf9f8",
        "inverse-on-surface": "#f3f0ef",
        "on-secondary-fixed-variant": "#474747",
        "surface-bright": "#fcf9f8"
      },
      fontFamily: {
        "headline": ["Playfair Display", "serif"],
        "body": ["Outfit", "sans-serif"],
        "label": ["Outfit", "sans-serif"]
      },
      borderRadius: { "DEFAULT": "0px", "lg": "0px", "xl": "0px", "full": "9999px" },
    },
  },
  plugins: [],
};
